DiegoRodriguez/DiegoRodriguez/Components/ProvinciaComunidadViewComponent.cs
using DiegoRodriguez.Services;
using Microsoft.AspNetCore.Mvc;

namespace DiegoRodriguez.Components
{
    public class ProvinciaComunidadViewComponent : ViewComponent
    {
        public IProvinciaRepositorio ProvinciaRepositorio { get; set; }
        public ProvinciaComunidadViewComponent(IProvinciaRepositorio ProvinciaRepositorio)
        {
            this.ProvinciaRepositorio = ProvinciaRepositorio;
        }
        public IViewComponentResult Invoke()
        {
            return View(ProvinciaRepositorio.provinciasPorComunidad());
        }

    }
}

DiegoRodriguez/DiegoRodriguez/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DiegoRodriguez.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

DiegoRodriguez/DiegoRodriguez/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DiegoRodriguez.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

DiegoRodriguez/DiegoRodriguez/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DiegoRodriguez.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

DiegoRodriguez/DiegoRodriguez/Pages/Provincias/Index.cshtml.cs
using DiegoRodriguez.Modelos;
using DiegoRodriguez.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DiegoRodriguez.Pages.Provincias
{
    public class IndexModel : PageModel
    {
		private readonly IProvinciaRepositorio ProvinciaRepositorio;
		public IEnumerable<Provincia> Provincias;

		[BindProperty(SupportsGet = true)]
		public Comunidad elementoABuscar { get; set; }

		public IndexModel(IProvinciaRepositorio ProvinciaRepositorio)
		{
			this.ProvinciaRepositorio = ProvinciaRepositorio;
		}

		public void OnGet()
        {
			Provincias = ProvinciaRepositorio.BuscarProvinciasPorComunidad(elementoABuscar);
        }
    }
}

DiegoRodriguez/DiegoRodriguez/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DiegoRodriguez/DiegoRodriguez/Pages/Provincias/Index.cshtml
@page
@using DiegoRodriguez.Modelos;
@model DiegoRodriguez.Pages.Provincias.IndexModel
@{
}
<h1>Provincias</h1>

<div class="col-sm-8">
    @await Component.InvokeAsync("ProvinciaComunidad")
</div>



<!--Desplegable para seleccionar una comunidad y que salgan sus provincias-->
<form method="get">
    <div class="form-group">
        <label asp-for="elementoABuscar" class="control-label">Filtrador de provincias por Comunidad</label>
        <select asp-for="elementoABuscar" class="form-control">
            @foreach (var value in Enum.GetValues(typeof(Comunidad)))
            {
                <option value="@((int)value)">@value</option>
            }
        </select>
    </div>
    <input type="submit" value="Filtrar" class="btn btn-primary" />
</form>

<br /><br />
<!--Mostrar todas las provincias con sus datos-->
@foreach (var provincia in Model.Provincias)
{
	<div class="card">
		<div class="card-body">
			<h5 class="card-title">@provincia.nomProvincia</h5>
			<p class="card-text">@provincia.numHabitantes </p>
			<p class="card-text">@provincia.superficie </p>
			<p class="card-text">@provincia.codComunidad</p>
		</div>
	</div>
}

DiegoRodriguez/DiegoRodriguez/Pages/Shared/Components/ProvinciaComunidad/Default.cshtml
@using DiegoRodriguez.Modelos
@model IEnumerable<ComunidadCuantos>

<h3>Provincias por Comunidad</h3>

<table class="table">
    <thead>
        <tr>
            <th>COMUNIDAD</th>
            <th>TOTAL SUPERFICIE</th>
            <th>TOTAL NUMERO HABITANTES</th>
            <th>TOTAL PROVINCIAS</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Comunidad</td>
                <td>@item.superficie</td>
                <td>@item.numHabitantes</td>
                <td>@item.numProvincias</td>
            </tr>
        }
    </tbody>
</table>

DiegoRodriguez/DiegoRodriguez/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DiegoRodriguez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DiegoRodriguez.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">DiegoRodriguez</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Provincias/Index">PROVINCIAS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DiegoRodriguez - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>