ProjectFutbol/ProjectFutbol/Components/EquipoCategoriaViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services;

namespace ProjectFutbol.Components
{
	public class EquipoCategoriaViewComponent : ViewComponent
	{
        public IEquiposRepositorio EquipoRepositorio { get; set; }  
        public EquipoCategoriaViewComponent(IEquiposRepositorio equipoRepositorio)
        {
            EquipoRepositorio = equipoRepositorio;
        }

        public IViewComponentResult Invoke()
        {
            var resultado = EquipoRepositorio.equiposPorCategoria();
			return View(resultado);
		}
    }
}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectFutbol.Pages.Equipos
{
    public class DeleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Modelos;
using Services;

namespace ProjectFutbol.Pages.Equipos
{
    public class DetailsModel : PageModel
    {
        public Equipo equipo { get; set; }
        private readonly IEquiposRepositorio equiposRepositorio;
        public DetailsModel(IEquiposRepositorio equiposRepositorio)
        {
            this.equiposRepositorio = equiposRepositorio;
        }
        public void OnGet(int id)
        {
            equipo = equiposRepositorio.GetEquipo(id);
        }
    }
}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Modelos;
using Services;

namespace ProjectFutbol.Pages.Equipos
{
    public class EditModel : PageModel
    {
        private readonly IEquiposRepositorio equipoRepositorio;
        public Equipo equipo { get; set; }

        public IFormFile Photo { get; set; }

        public EditModel(IEquiposRepositorio equipoRepositorio)
        {
            this.equipoRepositorio = equipoRepositorio;
        }
        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
				equipo = equipoRepositorio.GetEquipo(id.Value);
			}
			else
            {
				equipo = new Equipo();
			}
            return Page();
        }

        //Metodo onpost que guarde los cambios en el objeto equipo
        public IActionResult OnPost(Equipo equipo)
        {
            if (equipo.Id > 0)
            {
                equipoRepositorio.Update(equipo);
            }
			else
            {
				equipoRepositorio.InsertarEquipo(equipo);
			}
            return RedirectToPage("./Index");
		}

    }
}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Modelos;
using Services;

namespace ProjectFutbol.Pages.Equipos
{
    public class IndexModel : PageModel
    {
        private readonly IEquiposRepositorio equipoRepositorio;
        public IEnumerable<Equipo> Equipos;
        public Equipo equipo;
        [BindProperty(SupportsGet = true)]
        public string elementoABuscar { get; set; }
        public IndexModel(IEquiposRepositorio equipoRepositorio)
        {
            this.equipoRepositorio = equipoRepositorio;
        }
        public void OnGet()
        {
            Equipos = equipoRepositorio.BuscarEquipos(elementoABuscar);

		}
    }
}

ProjectFutbol/ProjectFutbol/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectFutbol.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ProjectFutbol/ProjectFutbol/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectFutbol.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ProjectFutbol/ProjectFutbol/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ProjectFutbol.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Delete.cshtml
@page
@model ProjectFutbol.Pages.Equipos.DeleteModel
@{
}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Details.cshtml
@page
@model ProjectFutbol.Pages.Equipos.DetailsModel
@{
    var photo = "~/fotoEquipo/" + (Model.equipo.Foto ?? "noimage.jpg");
}
<div class="card m-3" align="center" style="min-width: 12rem; max-width:80%">
    <div class="card-header">
        <h3>@Model.equipo.nomEquipo</h3>
    </div>
    <img class="card-img-top" width="250px" asp-append-version="true" src="@photo">
    <div class="card-footer text-center">
        <h3>Id: @Model.equipo.Id</h3>
        <h3>Nombre estadio: @Model.equipo.nomEstadio</h3>
        <h3>Categoría: @Model.equipo.categoria</h3>
    </div>

</div>

ProjectFutbol/ProjectFutbol/Pages/Equipos/Edit.cshtml
@page
@using Modelos;
@model ProjectFutbol.Pages.Equipos.EditModel
@{
	var photo = "~/fotoEquipo/" + (Model.equipo.Foto ?? "noimage.jpg");
	var titulo = Model.equipo.Id == 0 ? "Insertar Equipo" : "Editar Equipo";
}
<h1>@titulo</h1>
<!-- Formulario para modificar todos los campos de equipo-->

<form method="post" enctype="multipart/form-data">
	<input type="hidden" asp-for="equipo.Id" />
	<div class="form-group">
		<label asp-for="equipo.nomEquipo" class="control-label"></label>
		<input asp-for="equipo.nomEquipo" class="form-control" />
		<span asp-validation-for="equipo.nomEquipo" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="equipo.nomEstadio" class="control-label"></label>
		<input asp-for="equipo.nomEstadio" class="form-control" />
		<span asp-validation-for="equipo.nomEstadio" class="text-danger"></span>
	</div>
	<!--select de las categorias-->
	<div class="form-group">
		<label asp-for="equipo.categoria" class="control-label"></label>
		<select asp-for="equipo.categoria" class="form-select" 
			asp-items="Html.GetEnumSelectList<Categoria>()"></select>
		<span asp-validation-for="equipo.categoria" class="text-danger"></span>
	<div class="form-group">
		<label asp-for="equipo.Ciudad" class="control-label"></label>
		<input asp-for="equipo.Ciudad" class="form-control" />
		<span asp-validation-for="equipo.Ciudad" class="text-danger"></span>
	</div>
	<!--Mostrar foto y poder insertar un archivo con IFormFile para luego cambiar la imagen-->
	<div class="form-group">
		<label asp-for="equipo.Foto" class="control-label"></label>
		<img class="card-img-top" width="250px" asp-append-version="true" src="@photo">
		<input asp-for="equipo.Foto" class="form-control" type="file" id="Photo" />
		<span asp-validation-for="equipo.Foto" class="text-danger"></span>
	</div>


<!-- Boton submit para guardar los cambios y que lleva al index-->
	<div class="form-group">
		<input type="submit" value="Save" class="btn btn-primary" />
		<a asp-page="/Equipos/Index" class="btn btn-primary">Back to List</a>
	</div>

</form>


}

ProjectFutbol/ProjectFutbol/Pages/Equipos/Index.cshtml
@page
@model ProjectFutbol.Pages.Equipos.IndexModel
@{
}
	<h1>Equipos</h1>
	<!--Formulario para buscar alumnos-->
<form method="get">
		<div class="form-group">
			<input asp-for="elementoABuscar" class="control-label"></input>
			<input type="submit" value="Busca!"  class="btn btn-primary" />
		</div>
</form>

<div>
	@await Component.InvokeAsync("EquipoCategoria")
</div>

	@foreach(var equipo in Model.Equipos)
	{
		<div class="card">
			<div class="card-body">
				<h5 class="card-title">@equipo.nomEquipo</h5>
				<p class="card-text">@equipo.Ciudad</p>
				<a asp-page="/Equipos/Details" asp-route-ID="@equipo.Id" class="btn btn-primary m1">View</a>
				<a asp-page="/Equipos/Delete" asp-route-ID="@equipo.Id" class="btn btn-primary m1">Detele</a>
			</div>
		</div>
	}

ProjectFutbol/ProjectFutbol/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectFutbol/ProjectFutbol/Pages/Shared/EquipoCategoria/Default.cshtml
@model IEnumerable<CursoCuantos>
<h3>Equipos por categoria</h3>
<table class="table">
	<thead>
		<tr>
			<th>Categoria</th>
			<th>Numero de equipos</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>@item.categoria</td>
				<td>@item.cuantos</td>
			</tr>
		}
	</tbody>
</table>

ProjectFutbol/ProjectFutbol/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectFutbol</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectFutbol.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ProjectFutbol</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Equipos/Index">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Equipos/Edit">INSERTAR EQUIPO</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjectFutbol - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>